### ISSUE TITLE
border issue on mobile

### ISSUE THREAD

**Issue by rimmesbe** [jimtrippe/capstone2colmaracademy#1]
This border it creating a slight side scroll issues on your mobile sized site. Even border combined with 100% width can create a slight over stretch of the viewport. Make sure you take care of this on mobile.

https://github.com/jimtrippe/capstone2colmaracademy/blob/master/resources/css/style.css#L275

**Comment by jimtrippe** [comment]
Thanks for pointing this issue out, there were more than I cleaned up, appears I missed it.
