### ISSUE TITLE
semantic tags

### ISSUE THREAD

**Issue by rimmesbe** [jimtrippe/capstone2colmaracademy#3]
I like that you are incorporating more semantic tags into you html. Keep it up and keep introducing more semantic tags into your tool-box as there are many. I like this article for structuring with semantic tags:
https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

https://github.com/jimtrippe/capstone2colmaracademy/blob/master/index.html#L163

**Comment by jimtrippe** [comment]
Thank you, I have been transitioning.
