### ISSUE TITLE
class naming conventions

### ISSUE THREAD

**Issue by rimmesbe** [jimtrippe/capstone2colmaracademy#4]
Try to avoid class names like: left, right, middle. This makes your code more rigid and less reusable. Websites tend to change a lot so you want your code to be modular and flexible. Check out this official css naming convention: http://getbem.com/introduction/

https://github.com/jimtrippe/capstone2colmaracademy/blob/master/resources/css/style.css#L185

**Comment by jimtrippe** [comment]
Great tip, I remember thinking it was too rigid when I was working with them.  I will read the suggested article and modify my approach.
