### ISSUE TITLE
long chained selectors

### ISSUE THREAD

**Issue by rimmesbe** [jimtrippe/capstone2colmaracademy#5]
Much like positional depended selector names, long chains are very dependent on a specific layout. If any part of the design is changed these selectors will break and need to be rewritten. The smaller the chain the better, if it get 3+ long start looking to make a new class.

https://github.com/jimtrippe/capstone2colmaracademy/blob/master/resources/css/style.css#L338-L339

**Comment by jimtrippe** [comment]
I was concerned when I committed those selectors.  I will work around it in the future.  Thank you.
