### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [jimtrippe/capstone2colmaracademy#6]
Grade: Exceeds expectations

Summary: Really nice job on this project, the site looks really good on desktop and mobile. Your code is well organized and you used a lot of good techniques. I created a few issues with some minor tweaks and references to more techniques you can start implementing. Well done, I hope you enjoyed the course!

Here are some even more advanced semantic tags: http://learn.shayhowe.com/advanced-html-css/semantics-accessibility/

**Comment by jimtrippe** [comment]
Thanks, Ryan, I have been enjoying the class and the interactions and support.
